[versions]

java = "21"

kcml = "1.1.2"
iridium = "1.7.0.0-SNAPSHOT" # https://github.com/karmakrafts/Iridium/tags
kotlin = "2.2.10" # https://github.com/JetBrains/kotlin/releases
kotlinx-serialization = "1.9.0" # https://github.com/Kotlin/kotlinx.serialization/releases
dokka = "2.0.0" # https://github.com/Kotlin/dokka/releases"
karmaConventions = "1.5.5" # https://github.com/karmakrafts/karma-conventions/tags
autoService = "1.1.1" # https://github.com/google/auto/releases
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
kotlinGraphs = "0.6.1" # https://github.com/alexandrepiveteau/kotlin-graphs/releases
semver = "3.0.0" # https://github.com/z4kn4fein/kotlin-semver/releases
ow2asm = "9.8" # https://gitlab.ow2.org/asm/asm/-/tags
shadow = "9.0.2" # https://github.com/GradleUp/shadow/releases

[libraries]

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-native-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-native-compiler-embeddable", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
iridium = { module = "dev.karmakrafts.iridium:iridium", version.ref = "iridium" }
kotlinGraphs = { module = "io.github.alexandrepiveteau:kotlin-graphs", version.ref = "kotlinGraphs" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
ow2-asm-core = { module = "org.ow2.asm:asm", version.ref = "ow2asm" }
ow2-asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "ow2asm" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }