[versions]

java = "21"

kotlinBootstrap = "2.4.0" # https://github.com/JetBrains/kotlin/blob/v2.4.10/gradle.properties#L42
kotlin = "2.4.10" # https://github.com/JetBrains/kotlin/releases

kcml = "1.0.0"
iridium = "1.13.2" # https://github.com/karmakrafts/Iridium/tags
kotlinx-serialization = "1.11.0" # https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-coroutines = "1.11.0"
dokka = "2.2.0" # https://github.com/Kotlin/dokka/releases"
karmaConventions = "1.18.3" # https://github.com/karmakrafts/karma-conventions/tags
autoService = "1.1.1" # https://github.com/google/auto/releases
semver = "3.1.0" # https://github.com/z4kn4fein/kotlin-semver/releases
ow2asm = "9.10.1" # https://gitlab.ow2.org/asm/asm/-/tags
shadow = "9.6.0" # https://github.com/GradleUp/shadow/releases
kotlinGraphs = "0.6.1" # https://github.com/alexandrepiveteau/kotlin-graphs/releases
annotations = "26.1.0" # https://github.com/JetBrains/java-annotations/releases

[libraries]

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-native-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-native-compiler-embeddable", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

autoService-processor = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }

iridium = { module = "dev.karmakrafts.iridium:iridium", version.ref = "iridium" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
kotlinGraphs = { module = "io.github.alexandrepiveteau:kotlin-graphs", version.ref = "kotlinGraphs" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

ow2-asm-core = { module = "org.ow2.asm:asm", version.ref = "ow2asm" }
ow2-asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "ow2asm" }

[plugins]

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinBootstrap" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinBootstrap" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinBootstrap" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }