/*
 * Copyright 2026 Karma Krafts
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.karmakrafts.kcml.api.backend.llvm

import dev.karmakrafts.kcml.api.backend.Backend
import dev.karmakrafts.kcml.api.backend.BackendType
import dev.karmakrafts.kcml.api.target.NativeCompileTarget
import kotlinx.cinterop.ExperimentalForeignApi
import llvm.LLVMContextRef
import llvm.LLVMModuleRef
import org.jetbrains.kotlin.backend.konan.NativeCompilationConfig
import org.jetbrains.kotlin.backend.konan.NativeSecondStageCompilationConfig
import org.jetbrains.kotlin.backend.konan.driver.NativePhaseContext
import org.jetbrains.kotlin.backend.konan.ir.BackendNativeSymbols
import org.jetbrains.kotlin.builtins.konan.KonanBuiltIns
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.ir.IrBuiltIns

/**
 * Exposes Kotlin/Native backend state to KCML extensions.
 *
 * In addition to the common IR services, this context provides the Konan compilation state and
 * LLVM objects used while Kotlin/Native lowers IR to native code.
 */
@OptIn(ExperimentalForeignApi::class)
interface LateNativeBackend : Backend {
    /** Identifies this context as the late Kotlin/Native backend. */
    override val type: BackendType
        get() = BackendType.LateNative

    /** Native compilation target processed during LLVM code generation. */
    override val compileTarget: NativeCompileTarget

    /** Built-in IR definitions provided by Kotlin */
    val irBuiltIns: IrBuiltIns

    /** Kotlin/Native built-ins for the active Konan compilation. */
    val builtIns: KonanBuiltIns

    /** Kotlin/Native backend symbols resolved for the active compilation. */
    val symbols: BackendNativeSymbols

    /** Native compiler phase context that owns the current backend state. */
    val phaseContext: NativePhaseContext

    /** Configuration for Kotlin/Native's second-stage compilation pipeline. */
    val secondStageConfig: NativeSecondStageCompilationConfig

    /** LLVM context receiving native code generated by the Kotlin/Native backend. */
    val llvmContext: LLVMContextRef

    /** LLVM module produced for the compilation currently being lowered. */
    val llvmModule: LLVMModuleRef

    /** Native compilation configuration obtained from [phaseContext]. */
    val nativeConfig: NativeCompilationConfig
        get() = phaseContext.config

    /** Kotlin compiler configuration used by the native compilation. */
    override val config: CompilerConfiguration
        get() = nativeConfig.configuration
}